<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试报告</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--    页面样式-->
    <style type="text/css">
        /*标题样式*/
        .title {
            width: auto;
            height: 60px;
            text-align: center;
            font: bolder 38px/60px "Microsoft YaHei UI";
        }

        /*汇总信息样式*/
        .summary {
            width: 90%;
            position: absolute;
            top: 120px;
            margin-left: 5%;

        }

        .text-left {
            font: bolder 20px/30px "Microsoft YaHei UI";
        }

        .left {
            width: 50%;
            float: left;

        }

        .right {
            width: 50%;
            float: right;

        }

        .desc {
            float: left;
            width: 100%;
        }

        .list-group-item span {
            font: normal 16px/38px "Microsoft YaHei UI";
            padding: 30px;

        }

        .list-group-item {
            position: relative;
            display: block;
            padding: .4rem 1.25rem;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, .125);
        }

        /* 执行信息样式   */
        .test_info {
            width: 90%;
            position: absolute;
            top: 900px;
            margin-left: 5%;

            color: #28a745 !important;
        }

        .table td, th {
            border: solid 2px rgba(9, 122, 51, 0.11) !important;
            padding: 0;
            line-height: 40px;
            text-align: center;

        }


        select {
            border: 0;
            padding: 0;
            margin: 0;
            height: 2em;
            width: 8em;
            margin-left: 2em;
        }

        option {
            text-align: center;
            height: 36px;
            font: none 18px/36px "Microsoft YaHei UI";
            color: #28a745 !important;
        }

        .test_log {
            background: rgba(163, 171, 189, 0.15);
            width: 100%;
            height: 50px;
            border-top: none;
            border-bottom: none;
            display: none;
            text-align: left;
        }

        .test_log td {
            text-align: left;
            height: 30px;
            margin: 0;
            padding-left: 3em;
            padding-right:3em;
            font: none 18px/24px "Microsoft YaHei UI";
            color: #9e141a;
        }

        pre {
            margin: 0;
            white-space: pre-wrap;
            white-space: -moz-pre-wrap;
            white-space: -o-pre-wrap;
            word-wrap: break-word;
        }

        /*    测试图表显示*/
        .char {
            width: 90%;
            position: absolute;
            top: 450px;
            margin-left: 5%;
            color: #28a745 !important;
        }

    </style>

</head>
<body>

<!--报告标题-->
<div class="title text-success">
    <div class="shadow-lg p-3 mb-5 bg-white rounded">接口自动化测试报告</div>
</div>

<!--汇总信息-->
<div class="summary">
    <p class="text-left text-success">测试结果汇总</p>
    <div class="left">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">测试人员</button>
                <span class="text-dark">bty</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">开始时间</button>
                <span class="text-dark">2021-05-09 16:52:09</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">执行时间</button>
                <span class="text-dark">62.61 S</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">用例总数</button>
                <span class="text-dark">42</span>
            </li>


        </ul>
    </div>
    <div class="right">
        <ul class="list-group">

            <li class="list-group-item">
                <button type="button" class="btn btn-success">成功用例</button>
                <span class="text-success">35</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-danger">失败用例</button>
                <span class="text-warning">7</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-warning">错误用例</button>
                <span class="text-danger">0</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-secondary">跳过用例</button>
                <span class="text-secondary">0</span>
            </li>
        </ul>
    </div>
    <div class="desc">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">描述信息</button>
                <span class="text-secondary">接口复习</span>
            </li>
        </ul>
    </div>


</div>

<!--测试图表-->
<div class="char">
    <p class="text-left text-success">图表展示</p>
    <div id="char2" style="width: 49%;height: 400px;float: left"></div>
    <div id="char" style="width: 49%;height: 400px ;float: left"></div>
</div>

<!--详细信息-->
<div class="test_info">

    <p class="text-left text-success">详细信息</p>
    <div class="table_data">

        <table class="table">
            <thead class="bg-success text-light">
            <tr>
                <th scope="col" style="width: 5%;padding: 0">编号</th>
                <th scope="col" style="width: 20%;padding: 0">
                    <span>测试类</span>
                    <select id="testClass">
                        <option>所有</option>
                        
                            <option>TestRegister</option>
                        
                            <option>TestLogin</option>
                        
                            <option>TestRecharge</option>
                        
                    </select>

                </th>

                <th scope="col" style="width: 15%;padding: 0">测试方法</th>
                <th scope="col" style="width: 20%;padding: 0">用例描述</th>
                <th scope="col" style="width: 10%;padding: 0">执行时间</th>
                <th scope="col" style="width: 20%;padding: 0">

                    <span>执行结果</span>
                    <select id="testResult">
                        <option>所有</option>
                        <option class="text-success">成功</option>
                        <option class="text-danger">失败</option>
                        <option class="text-warning">错误</option>
                        <option class="text-info">跳过</option>
                    </select>

                </th>
                <th scope="col" style="width: 10%;padding: 0">详细信息</th>
            </tr>
            </thead>
            <tbody>
            
                <tr>
                    <td>1</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_01</td>
                    <td>注册成功-带注册名</td>
                    <td>1.38s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524853, 'reg_name': 'bty', 'mobile_phone': '18509673812'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_01 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>2</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_02</td>
                    <td>注册成功-不带注册名</td>
                    <td>2.25s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524864, 'reg_name': '小柠檬', 'mobile_phone': '15823097568'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_02 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>3</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_03</td>
                    <td>注册成功-不带类型和注册名</td>
                    <td>2.15s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524883, 'reg_name': '小柠檬', 'mobile_phone': '15027980615'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_03 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>4</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_04</td>
                    <td>注册成功-不带类型</td>
                    <td>2.75s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524898, 'reg_name': 'bty', 'mobile_phone': '13016284597'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_04 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>5</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_05</td>
                    <td>注册成功-类型为0</td>
                    <td>2.18s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524917, 'reg_name': 'bty', 'mobile_phone': '13547302156'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_05 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>6</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_06</td>
                    <td>注册失败-不带手机号</td>
                    <td>0.237s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 1, 'msg': '手机号为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_06 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>7</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_07</td>
                    <td>注册失败-不带密码</td>
                    <td>0.235s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_07 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>8</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_08</td>
                    <td>注册失败-手机号长度为10</td>
                    <td>0.253s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_08 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>9</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_09</td>
                    <td>注册失败-手机号长度为12</td>
                    <td>0.268s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_09 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>10</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_10</td>
                    <td>注册失败-手机号中存在非法字符</td>
                    <td>0.232s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_10 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>11</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_11</td>
                    <td>注册失败-密码7位</td>
                    <td>0.241s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '密码格式为8到16位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_11 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>12</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_12</td>
                    <td>注册失败-密码17位</td>
                    <td>0.219s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '密码格式为8到16位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_12 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>13</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_13</td>
                    <td>注册失败-注册名11位</td>
                    <td>0.209s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '用户昵称长度超过10位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_13 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>14</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_14</td>
                    <td>注册失败-类型输入非0，1内容</td>
                    <td>0.257s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 2, 'msg': '不支持的用户类型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_14 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>15</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_15</td>
                    <td>注册成功-注册名为null</td>
                    <td>1.27s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524950, 'reg_name': '小柠檬', 'mobile_phone': '13873986124'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_15 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>16</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_16</td>
                    <td>注册失败-类型为null</td>
                    <td>1.96s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 0, 'msg': 'OK', 'data': {'id': 1000524966, 'reg_name': 'bty', 'mobile_phone': '13162803174'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_16 (test01_register.TestRegister)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test01_register.py", line 72, in test_register
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test01_register.py", line 58, in test_register
    res_asser_expected(expected, res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '不支持的用户类型'} not in {'code': 0, 'msg': 'OK', 'data': {'id': 1000524966, 'reg_name': 'bty', 'mobile_phone': '13162803174'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>17</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_17</td>
                    <td>注册失败-手机号为null</td>
                    <td>0.224s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 1, 'msg': '手机号为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_17 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>18</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_18</td>
                    <td>注册失败-密码为null</td>
                    <td>0.224s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>请求结果 {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_18 (test01_register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>19</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_01</td>
                    <td>登录成功</td>
                    <td>1.61s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_01 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>20</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_02</td>
                    <td>登录失败-账号为空</td>
                    <td>0.244s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_02 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>21</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_03</td>
                    <td>登录失败-密码为空</td>
                    <td>0.238s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_03 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>22</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_04</td>
                    <td>登录失败-错误的账号</td>
                    <td>1.74s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_04 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>23</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_05</td>
                    <td>登录失败-未注册的账号</td>
                    <td>1.71s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_05 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>24</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_06</td>
                    <td>登录失败-错误的密码</td>
                    <td>1.88s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_06 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>25</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_07</td>
                    <td>登录失败-手机格式错误</td>
                    <td>0.247s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_07 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>26</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_08</td>
                    <td>登录失败-手机格式错误</td>
                    <td>0.24s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>test_login_08 (test02_login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>27</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_01</td>
                    <td>充值成功-金额为正整数</td>
                    <td>2.38s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20618004.10'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20618004.10'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20618604.10'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20618604.10'),)
test_recharge_01 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>28</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_02</td>
                    <td>充值成功-金额为1位小数</td>
                    <td>2.29s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20618604.10'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20618604.10'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619204.20'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619204.20'),)
test_recharge_02 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>29</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_03</td>
                    <td>充值成功-金额为2位小数</td>
                    <td>2.45s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619204.20'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619204.20'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
test_recharge_03 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>30</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_04</td>
                    <td>充值失败-金额为3位小数</td>
                    <td>2.59s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
test_recharge_04 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>31</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_05</td>
                    <td>充值失败-金额为0</td>
                    <td>2.85s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('20619804.42'),)
test_recharge_05 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'} not in {'code': 0, 'msg': 'OK', 'data': {'id': 10018244, 'leave_amount': 20619804.42, 'mobile_phone': '13262664317', 'reg_name': '小柠檬', 'reg_time': '2021-02-22 20:28:34.0', 'type': 0}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>32</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_06</td>
                    <td>充值成功-金额499999.99</td>
                    <td>2.05s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('20619804.42'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('21119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('21119804.41'),)
test_recharge_06 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>33</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_07</td>
                    <td>充值成功-金额50万整</td>
                    <td>1.74s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('21119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('21119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('21619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('21619804.41'),)
test_recharge_07 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>34</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_08</td>
                    <td>充值成功-金额500000.0</td>
                    <td>2.61s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('21619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('21619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22119804.41'),)
test_recharge_08 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>35</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_09</td>
                    <td>充值成功-金额500000.00</td>
                    <td>2.93s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22119804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_09 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>36</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_10</td>
                    <td>充值失败-金额大于50万</td>
                    <td>2.36s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_10 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'} not in {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>37</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_11</td>
                    <td>充值失败-金额为负数</td>
                    <td>2.95s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_11 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'} not in {'code': 2, 'msg': '余额必须大于0并且小于或者等于500000', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>38</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_12</td>
                    <td>充值失败-金额为字母</td>
                    <td>2.08s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_12 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '数字格式化异常'} not in {'code': 2, 'msg': '余额必须为数值型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>39</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_13</td>
                    <td>充值失败-金额为特殊字符</td>
                    <td>2.37s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_13 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 2, 'msg': '数字格式化异常'} not in {'code': 2, 'msg': '余额必须为数值型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>40</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_14</td>
                    <td>充值失败-id为空</td>
                    <td>1.56s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_14 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>41</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_15</td>
                    <td>充值失败-id为小数</td>
                    <td>1.65s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_15 (test03_recharge.TestRecharge)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>42</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_16</td>
                    <td>充值失败-错误的id</td>
                    <td>2.24s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 82, in test_recharge
    my_log.info("请求之前的金额为：",start_amount)
Message: '请求之前的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
--- Logging error ---
Traceback (most recent call last):
  File "E:\python\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "E:\python\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "E:\python\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "E:\python\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\python\lib\threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "E:\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "E:\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\python\lib\unittest\suite.py", line 122, in run
    test(result)
  File "E:\python\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 91, in test_recharge
    my_log.info("请求之后的金额为：",end_amount)
Message: '请求之后的金额为：'
Arguments: (Decimal('22619804.41'),)
test_recharge_16 (test03_recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "E:\python\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "E:\python\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 108, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\testcases\test03_recharge.py", line 94, in test_recharge
    res_asser_expected(expected,res)
</pre>
                        

                            <pre>  File "D:\pyhton_api\api_fuxi\common\handle_com.py", line 46, in res_asser_expected
    raise AssertionError("{} not in {}".format(expected, res))
</pre>
                        

                            <pre>AssertionError: {'code': 1, 'msg': '用户id错误'} not in {'code': 1007, 'msg': '无权限访问，请检查参数', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
</pre>
                        
                        
                    </td>
                </tr>
            

            </tbody>
        </table>
    </div>

    <div style="height: 200px"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>

<script>
    var tbodyTr = $('tbody tr');
    var testResult = $("#testResult");
    var testClass = $("#testClass");
    <!--    用例执行详细信息显示切换-->
    $(".btn_info").click(function () {
        $(this).parent().parent().next().toggle();

    });
    // 当选择用例类之后触发
    testClass.change(function () {
        var cls = $(this).val();
        var res = testResult.val();
        elementDisplay(cls, res);
        sort()
    });
    testResult.change(function () {
        var res = $(this).val();
        var cls = testClass.val();
        elementDisplay(cls, res);
        sort()
    });

    function elementDisplay(cls, res) {
        // 用例数据的显示
        if (cls === "所有") {
            if (res === "所有") {
                tbodyTr.has('button').show();
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-success').show()

            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-danger').show()

            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-warning').show()

            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-info').show()
            }
        } else {
            if (res === "所有") {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').show()
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-success').show()
            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-danger').show()
            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-warning').show()
            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-info').show()
            }
        }
    }

    function sort() {
        //重新排列显示序号
        // 选择所有可以见的tr
        var visibleTr = tbodyTr.filter(":visible");

        visibleTr.each(function (index, element) {
            element.firstElementChild.innerHTML = index + 1;

        })

    }


</script>

<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('char'));
    var myChart2 = echarts.init(document.getElementById('char2'));
    // 指定图表的配置项和数据
    option = {
        color: ['#00a10a', '#ddb518', 'rgba(204,46,41,0.73)', '#85898c'],
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b}: {c} ({d}%)'
        },
        legend: {
            orient: 'vertical',
            left: 10,
            data: ['通过', '失败', '错误', '跳过']
        },
        series: [
            {
                name: '测试结果',
                type: 'pie',
                radius: ['50%', '70%'],
                avoidLabelOverlap: false,
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                        show: true,
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [
                    {value: 35, name: '通过'},
                    {value: 7, name: '失败'},
                    {value: 0, name: '错误'},
                    {value: 0, name: '跳过'}
                ]
            }
        ]
    };
    option2 = {
        tooltip: {
            formatter: '{a} <br/>{b} : {c}%'
        },
        toolbox: {
            feature: {
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                name: '测试结果',
                type: 'gauge',
                detail: {formatter: '83.33%'},
                data: [{value: '83.33', name: '用例通过率'}],
                axisLine: {
                    lineStyle: {
                        color: [
                            [0.2, '#c20000'],
                            [0.8, '#ddb518'],
                            [1, '#00a10a']]
                    }
                }
            }
        ]
    };


    myChart2.setOption(option2);
    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>


</body>
</html>